<a href="https://colab.research.google.com/github/J-Lmb/Hamoye/blob/master/Quiz_draft_code.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [47]:
a = [1,2,3,4,5,6]
b = [13, 21, 34]

In [48]:
print(a.extend(b))

None


In [49]:
import numpy as np 

In [53]:
a = np.eye(3)

In [54]:
print(a)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [57]:
c = np.array([[1,0,0],[0,1,0]])

In [ ]:
import pandas as pd

In [62]:
url='https://raw.githubusercontent.com/WalePhenomenon/climate_change/master/fuel_ferc1.csv'
fuel_data = pd.read_csv(url, error_bad_lines=False)
fuel_data.describe(include='all')
fuel_data.head(10)

record_id  ...  fuel_cost_per_mmbtu
0   f1_fuel_1994_12_1_0_7  ...                1.121
1  f1_fuel_1994_12_1_0_10  ...                1.120
2   f1_fuel_1994_12_2_0_1  ...                1.650
3   f1_fuel_1994_12_2_0_7  ...                1.970
4  f1_fuel_1994_12_2_0_10  ...                2.570
5  f1_fuel_1994_12_2_0_13  ...                1.850
6   f1_fuel_1994_12_2_1_1  ...                0.450
7  f1_fuel_1994_12_2_1_10  ...                2.360
8  f1_fuel_1994_12_2_2_10  ...                1.400
9   f1_fuel_1994_12_4_0_1  ...                1.278

[10 rows x 11 columns]

In [63]:
fuel_data[['fuel_cost_per_unit_burned']].idxmin() 

fuel_cost_per_unit_burned    7733
dtype: int64

In [64]:
fuel_data.iloc[7733]

record_id                       f1_fuel_2000_12_194_3_3
utility_id_ferc1                                    194
report_year                                        2000
plant_name_ferc1                    nelson dewey unit 2
fuel_type_code_pudl                               waste
fuel_unit                                           ton
fuel_qty_burned                                      39
fuel_mmbtu_per_unit                              0.0155
fuel_cost_per_unit_burned                       -276.08
fuel_cost_per_unit_delivered                    -174.67
fuel_cost_per_mmbtu                              -8.906
Name: 7733, dtype: object

In [65]:
fuel_data['fuel_mmbtu_per_unit'].mean()

8.49211066832643

In [83]:
fuel_data['fuel_mmbtu_per_unit'].quantile(0.75)

17.006

In [70]:
print(fuel_data.kurt(axis=1))

0        6.999997
1        6.999999
2        6.999990
3        6.999994
4        6.945907
           ...   
29518    6.737906
29519    6.999864
29520    6.991838
29521    6.999116
29522    6.708633
Length: 29523, dtype: float64


In [72]:
fuel_data['fuel_qty_burned'].skew()

15.851495469109503

In [73]:
# check for cells with missing values as True
fuel_data.isnull()


record_id  ...  fuel_cost_per_mmbtu
0          False  ...                False
1          False  ...                False
2          False  ...                False
3          False  ...                False
4          False  ...                False
...          ...  ...                  ...
29518      False  ...                False
29519      False  ...                False
29520      False  ...                False
29521      False  ...                False
29522      False  ...                False

[29523 rows x 11 columns]

In [77]:
fuel_data.isna().sum()/len(fuel_data)

record_id                       0.000000
utility_id_ferc1                0.000000
report_year                     0.000000
plant_name_ferc1                0.000000
fuel_type_code_pudl             0.000000
fuel_unit                       0.006097
fuel_qty_burned                 0.000000
fuel_mmbtu_per_unit             0.000000
fuel_cost_per_unit_burned       0.000000
fuel_cost_per_unit_delivered    0.000000
fuel_cost_per_mmbtu             0.000000
dtype: float64

In [80]:
fuel_data.groupby('fuel_cost_per_unit_delivered').mean()

utility_id_ferc1  ...  fuel_cost_per_mmbtu
fuel_cost_per_unit_delivered                    ...                     
-874.937                                 177.0  ...               15.055
-488.054                                 177.0  ...               13.487
-313.410                                 210.0  ...                6.779
-174.670                                 194.0  ...               -6.173
-170.187                                   6.0  ...               21.608
...                                        ...  ...                  ...
 1942979.000                               9.0  ...                0.560
 2114508.000                               9.0  ...                0.095
 2255688.000                               9.0  ...                1.087
 7793482.000                               9.0  ...                0.145
 7964521.000                               9.0  ...                0.578

[16675 rows x 6 columns]